id: PE688880A
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ296779
  title: རྒྱ་གཞུང་གནད་ཆེ་བདམ་བསྒྲིགས།
  volumes:
    00f046bc319142d08b4778dde2241683:
      image_group_id: I4CZ298999
      title: ''
      base_file: v001.txt
  author: ''
